FROM node:20-slim
COPY --from=ghcr.io/astral-sh/uv:0.9.22 /uv /uvx /usr/local/bin/
COPY --from=ghcr.io/jqlang/jq:1.8.1 /jq /usr/local/bin/

WORKDIR /opt/npm-tools
COPY npm-tools/package.json npm-tools/package-lock.json ./
RUN npm ci --omit=dev
ENV PATH="/opt/npm-tools/node_modules/.bin:${PATH}"

WORKDIR /work
CMD bash

# Install openapi-python-client via uvx
RUN uv tool install --python=3.9 openapi-python-client==0.21.5
RUN ln -s /root/.local/bin/openapi-python-client /usr/local/bin/
RUN openapi-python-client --help
