name: Performance tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: gcp-perf-test-dedicated
    container:
      image: ubuntu:24.04
      options: --cpus 1
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y git

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip &&
          pip install -r dev_requirements.txt

      - name: Run performance tests
        env:
          BENCHMARK_NO_VALIDATION: "1"
        run: |
          pytest --junitxml="test-results/test-performance.xml" tests/performance
