name: Performance tests

permissions:
  checks: write

on:
  schedule:
    - cron: '0 8 * * *' # Run at 8:00 daily
  workflow_dispatch:
  push:
#  pull_request:
#    paths:
#      - 'src/**'
#      - 'tests/**'
#      - 'dev_requirements.txt'
#      - 'pyproject.toml'
#      - '.github/workflows/tests-performance.yml'

jobs:
  test:
    runs-on: gcp-perf-test-dedicated
    container:
      image: ubuntu:24.04
      options: --cpuset-cpus=0
    timeout-minutes: 30
    steps:
      - name: Install Git
        run: |
          apt-get update && apt-get install -y git &&
          git config --global --add safe.directory /__w/neptune-query/neptune-query

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.13"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip &&
          pip install -r dev_requirements.txt

      - name: Run performance tests
        run: |
          pytest --junitxml="test-results/test-performance.xml" tests/performance

      - name: Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          check_name: 'Performance tests report'
          report_paths: "./test-results/test-performance.xml"
          detailed_summary: true
          verbose_summary: true
          include_passed: true
          include_time_in_summary: true
          resolve_ignore_classname: true
