name: Performance tests

on:
  schedule:
    - cron: '0 8 * * *' # Run at 8:00 daily
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/.*
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'dev_requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/tests-performance.yml'

jobs:
  test:
    runs-on: tools-gha-runners
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip &&
          pip install -r dev_requirements.txt

      - name: (Optional) Collect performance data
        env:
            BENCHMARK_NO_VALIDATION: "1"
        run: |
          pytest tests/performance

      - name: Validate performance data
        run: |
          pytest --junitxml="test-results/test-performance.xml" tests/performance

      - name: Report
        uses: mikepenz/action-junit-report@v5
        if: always()
        with:
          report_paths: "./test-results/test-performance*.xml"
          update_check: true
          annotate_notice: true
          job_name: "Performance tests"
