name: Run fuzzy tests - neptune-query

on:
  schedule:
    - cron: '0 8 * * *' # Run at 8:00 daily
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/.*
  pull_request:
    paths:
      - 'src/**'
      - 'tests/fuzzy/**'
      - 'dev_requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/tests-fuzzy.yml'

jobs:
  test:
    timeout-minutes: 75
    strategy:
      fail-fast: false
      matrix:
        python-version: [ "3.13" ]
        os: [ ubuntu ]

    name: 'fuzzy test (${{ matrix.os }} - py${{ matrix.python-version }})'
    runs-on: ${{ matrix.os }}-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ github.event.client_payload.pull_request.head.ref }}

      - name: Install package
        uses: ./.github/actions/install-package
        with:
          python-version: ${{ matrix.python-version }}
          os: ${{ matrix.os }}-latest

      - name: Run tests
        uses: ./.github/actions/run-tests
        with:
          test-directory: fuzzy
          report-job: 'test fuzzy (${{ matrix.os }} - py${{ matrix.python-version }})'
          report-suffix: 'fuzzy-${{ matrix.python-version }}-${{ matrix.os }}'
          timeout: "900"
        env:
          NEPTUNE_E2E_HYPOTHESIS_PROFILE: ${{ github.event_name == 'schedule' && 'ci-nightly' || 'ci-quick' }}

      - name: Notify on failure
        if: failure() && github.event_name == 'schedule'
        uses: ./.github/actions/workflow-notify
        with:
          slack-webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          failure-message: "Fuzzy tests failed"
