name: Performance tests

on:
  schedule:
    - cron: '0 8 * * *' # Run at 8:00 daily
  workflow_dispatch:
  push:
    branches:
      - main
      - dev/.*
  pull_request:
    paths:
      - 'src/**'
      - 'tests/**'
      - 'dev_requirements.txt'
      - 'pyproject.toml'
      - '.github/workflows/tests-performance.yml'

jobs:
  test:
    runs-on: gcp-perf-test-dedicated
    container:
      image: ubuntu:24.04
      options: --cpus 1
    timeout-minutes: 30
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"

      - name: Install system dependencies
        run: |
          apt-get update && apt-get install -y git

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip &&
          pip install -r dev_requirements.txt

      - name: Run performance tests
        run: |
          pytest --junitxml="test-results/test-performance.xml" tests/performance
